name: meetup_uy
channels:
  - conda-forge
dependencies:
  - pip:
    - notebook=6.4.0
    - ipywidgets=7.6.3
    - widgetsnbextension=3.5.1
    - numpy=1.21.0
    - scikit-learn=0.24.2
    - matplotlib=3.4.2
    - seaborn=0.11.1
    - pandas=1.3.0
    - xgboost=1.4.2
    - lightgbm=3.2.1
    - catboost=0.26