name: meetup_uy
channels:
  - conda-forge
dependencies:
  - notebook=5.7.8
  - nbconvert=5.4
  - widgetsnbextension=3.4
  - jupyter_nbextensions_configurator
  # Python Kernel
  - numpy==1.18.5
  - scikit-learn==0.23.1
  - matplotlib==3.2.2
  - seaborn==0.10.1
  - pandas==1.0.5