name: meetup_uy
channels:
  - conda-forge
dependencies:
  - python=3.12.10
  - pip=25.2
  - pip:
    - numpy=2.1.3
    - pandas=2.3.3
    - scikit-learn=1.7.2
    - scipy=1.15.3
    - matplotlib=3.10.0
    - seaborn=0.13.2
    - # Machine Learning
    - xgboost=3.1.1
    - lightgbm=4.6.0
    - catboost=1.2.8
    - optuna=4.5.0
    - shap=0.49.1
    - # Jupyter Environment
    - notebook=7.4.7
    - ipywidgets=8.1.7
    - widgetsnbextension=4.0.14
    - jupyterlab=4.4.10
    - # Data Profiling
    - ydata-profiling=4.17.0
    - # MLServer for Model Serving
    - mlserver=1.7.1
    - mlserver-sklearn=1.7.1
    - fastapi=0.115.14
    - uvicorn=0.38.0
    - # Google Cloud BigQuery
    - google-cloud-bigquery=3.38.0
    - pyarrow=21.0.0
    - # Utilities
    - tqdm=4.67.1
    - requests=2.32.5
    - python-dateutil=2.9.0.post0